<?binding.jca PollDb_db.jca?>
<wsdl:definitions name="PollDb" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProductServicesApp/PollDb/PollDb" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProductServicesApp/PollDb/PollDb" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollDb">
    <plt:partnerLinkType name="PollDb_plt">
        <plt:role name="PollDb_role">
            <plt:portType name="tns:PollDb_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollDb" schemaLocation="xsd/PollDb_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="WatchtableCollection_msg">
        <wsdl:part name="WatchtableCollection" element="top:WatchtableCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollDb_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:WatchtableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
