<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ReadCustomer.wsdl"/>
      <rootElement name="CustomerCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ReadCustomer"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Process.wsdl"/>
      <rootElement name="start" namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/Process"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [FRI FEB 14 13:15:45 PST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:tns6="http://www.sample.com/shopping"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/bpmn/bpmnProcess/Process"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ReadCustomer"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ShoppingApp/LoyaltyStatusMgmt/ReadCustomer"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl top tns xsd SOAP-ENC wsdlsoap tns6 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns0:start>
      <tns6:Customer>
        <tns6:customerId>
          <xsl:value-of select="/top:CustomerCollection/top:Customer[1]/top:customerId"/>
        </tns6:customerId>
        <tns6:firstName>
          <xsl:value-of select="/top:CustomerCollection/top:Customer[1]/top:firstName"/>
        </tns6:firstName>
        <tns6:lastName>
          <xsl:value-of select="/top:CustomerCollection/top:Customer[1]/top:lastName"/>
        </tns6:lastName>
        <tns6:email>
          <xsl:value-of select="/top:CustomerCollection/top:Customer[1]/top:email"/>
        </tns6:email>
        <tns6:totalPurchases>
          <xsl:value-of select="/top:CustomerCollection/top:Customer[1]/top:totalPurchases"/>
        </tns6:totalPurchases>
        <tns6:loyaltyStatus>
          <xsl:value-of select="/top:CustomerCollection/top:Customer[1]/top:loyaltyStatus"/>
        </tns6:loyaltyStatus>
        <tns6:procStatus>
          <xsl:value-of select="/top:CustomerCollection/top:Customer[1]/top:procStatus"/>
        </tns6:procStatus>
      </tns6:Customer>
    </ns0:start>
  </xsl:template>
</xsl:stylesheet>
